### ISSUE TITLE
[Question] Auditwheel-symbols and Auditwheel do not agree

### ISSUE THREAD

**Issue by DavidLapous** [messense/auditwheel-symbols#5]
Hi, and thanks for your work, this is really useful.
I have the following issue; I have a library that I'm packaging on pypi (here : https://github.com/DavidLapous/multipers)
on which I need [tbb](https://oneapi-src.github.io/oneTBB/) (which can be installed via pip/conda). 
 1. If I run your tool I end up with
 ```
 > auditwheel-symbols --manylinux 2_34 multipers-1.0-cp311-cp311-linux_x86_64.whl
 [...] is not manylinux_2_34 compliant because it links the following forbidden libraries:
libtbb.so.12
```
 2. But when I run the auditwheel show command
 ```
 > auditwheel show multipers-1.0-cp311-cp311-linux_x86_64.whl
 [...]
 
 This constrains the platform tag to "manylinux_2_34_x86_64". [...]
 ```
 And the repair succeeds with the `manylinux_2_34_x86_64` platform.
 
 Do you have an idea on who is right ?
 The repaired wheel indeed ships with `multipers.libs/libtbb-b726c00d.so.12` so it's taken into account, 
but I'm not sure if everything is compatible if your tool says its not the case.

**Comment by messense** [comment]
My guess is that `auditwheel show` detects that it can package `libtbb.so` so it's considered compliant, but this tool does not do that.
